version: '3.8'

networks:
  java:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - java
    ports:
    - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    networks:
      - java
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
